### ISSUE TITLE
Ionic is out of date

### ISSUE THREAD

**Issue by DrMabuse23** [zachsoft/Ionic-Material#10]
Hey Ionic released 1.0.0-rc.0  and beta 1.0 is out more then a half year why is there 0.9... ?

**Comment by benamib** [comment]
Hey Zach,
I couldn't get it to work with my project since I am using the latest Ionic version, could you do something about it ?
Thanks

**Comment by zachsoft** [comment]
Alpha will be released this week that is aimed at the current version of Ionic. Bower will be updated when the release is official.
