### ISSUE TITLE
Slow, Android device so slow and not good.

### ISSUE THREAD

**Issue by dungphanxuan** [zachsoft/Ionic-Material#101]
Hello, i;'ve test app on android device, so app run slow, slider page is delay and not good.

**Comment by edencoder** [comment]
Which android device specifically mate?

**Comment by codingL3gend** [comment]
have you tried building your app to run with crosswalk?

**Comment by dungphanxuan** [comment]
I'm run on galaxy a7, app run normally, but effect is not good.

**Comment by dungphanxuan** [comment]
@codingL3gend. No i build with ionic framework

**Comment by codingL3gend** [comment]
try using the crosswalk browser with your app. it should improve the experience

**Comment by sclausen** [comment]
ionic uses the crosswalk plugin by default.

**Comment by codingL3gend** [comment]
unless this is recent i thought it still needed to be added or bundled with the application either by downloading the crosswalk files and doing a update of the android platform using cordova or adding it using the ionic cli. i wasnt aware that it did it automatically now

**Comment by gtgt** [comment]
As I know ionic doesn't use crosswalk by default (maybe will in future, who knows).

You need update cli to newest version and add crosswalk by "ionic add crosswalk".

**Comment by khertan** [comment]
ionic browser add crosswalk

not really difficult to install but i ve notive strange behaviour with it and background plugin
