### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by babakness** [zachsoft/Ionic-Material#104]
With Ionic 2 being worked on that will break compatibility because of Angular 2 and no commit in almost a month--is this project still active? It's a great idea for sure.

**Comment by itrethan** [comment]
yeah? still active?

**Comment by sclausen** [comment]
+1

**Comment by mavrick** [comment]
It's only been a month fellas, calm down

**Comment by sclausen** [comment]
@mavrick I, for myself are really calm. Nobody has demanded anything, its a spare-time project and I think not just me, but the others too, respect that. A month in this sector is a really long time span and not very usual for projects in this rapid evolving sector. So asking for the status and not demanding anything is imho appropriate.

**Comment by NgYueHong** [comment]
Yeah, it is my first impression after seeing it's releases. It was extremely active during May. After that, "dead". 

Is it still active?

**Comment by JobaDiniz** [comment]
+1

**Comment by TonyLuo** [comment]
+1

**Comment by kreck** [comment]
+1

**Comment by lautarosrur** [comment]
+1

**Comment by NoellyB76** [comment]
I'd REALLY like to know myself! I've been advocating this everywhere.

**Comment by delta98** [comment]
V1 being released Aug 31st seemless integration with Ionic and a full roadmap of features and updates https://github.com/delta98/ionic-material-design-lite

**Comment by sclausen** [comment]
@delta98: Why did you remove your post about https://github.com/delta98/ionic-material-design-lite?
Seems like a nice alternative!

**Comment by delta98** [comment]
I moved it to a separate issue so that it wouldn't appear in such bad taste. Thanks for the support, it's a shame this project has stalled and if I weren't in disagreement with the approach I'd of picked it up.

But do check out the project https://github.com/delta98/ionic-material-design-lite it's purpose is to be seamless and require you not to have to use bespoke directives, something I disliked about Ionic Material.

**Comment by NgYueHong** [comment]
@delta98 Happy to see another alternative. Will try with it soon. Hopefully the performance is good as current Ionic-Material performance is totally unacceptable on low end smartphone.

**Comment by delta98** [comment]
Thanks. It's mainly CSS and utilises Google's Material Design Lite library so will be performant. I'm looking for people to test it to provide feedback for RC 1 release end of August.

Animations and transitions will be part of v1.1 once a stable release of CSS styles are available.

**Comment by oscarmcm** [comment]
Im working on it now :+1:

**Comment by sclausen** [comment]
:+1:

**Comment by abartolo** [comment]
Any update whether this is till being worked on? I see a lot of issues open that i am facing.

**Comment by sclausen** [comment]
@abartolo last commit is from october 2015. I may go out on a limb with this, but this project seems dead.
