### ISSUE TITLE
Not able to run the project in browser

### ISSUE THREAD

**Issue by vaibhavmalushte** [zachsoft/Ionic-Material#109]
Hi I got the following error when tried to run in Firefox / chrome 

Error: [$injector:modulerr] Failed to instantiate module starter due to:
[$injector:modulerr] Failed to instantiate module ionic-material due to:
[$injector:nomod] Module 'ionic-material' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Please advice.

Thank you,
Vaibhav

**Comment by cmauroie** [comment]
deleted www/lib/ionic-material and run 'bower install ionic-material' again. it worked.
now replaces line 13 of index.html with:
<script src="lib/ionic-material/dist/ionic.material.min.js"></script>

**Comment by vaibhavmalushte** [comment]
Thank you very much it did the trick :+1:
