### ISSUE TITLE
a problem with the position of header buttons

### ISSUE THREAD

**Issue by fanyhong** [zachsoft/Ionic-Material#111]
Hi ! 
First of all, thank you for offering this nice UI library.

I have a problem to attach this lib to my ionic app.
between before and after I attached this lib, the position of header buttons are changed.

As you can see this picture I captured, the header button of right side is not on right position. (some go down and left) and I think the position of the icons in buttons is on the right side a little.

I've just added .css and .js files of 'ionic-matrial' to index.html and injected 'ionic-material' to app.js of my original app. That's all I did.

Please check this, thank you.

**Comment by sbryfcz** [comment]
I'm not sure about the rest of the community but I've been setting my nav bar buttons class to button-clear. This seemed to fix it for me.

**Comment by fanyhong** [comment]
Thank you for reply.

I also tried to add 'button-clear' like this.
![20150715_213922](https://cloud.githubusercontent.com/assets/6311696/8698522/ffd98c80-2b39-11e5-8f71-bd97536305e6.png)

It's just looks fine, but the position of right-side-buttons is same as before.

when I try to add  some style like 'margin-top: -5px;' and 'margin-right: -5px;' to only right-side-button, it looks perfect like this.
![20150715_214438](https://cloud.githubusercontent.com/assets/6311696/8698641/be012c68-2b3a-11e5-9465-9793c2cc3008.png)

so, I think it needs to adjust something.
and when it doesn't have 'button-clear', the left-padding of the buttons of the header also needs.

**Comment by fanyhong** [comment]
I found the reason of my problem through lots of tests.. 
That was ionic-framework version issue.
Mine was old version (v1.0.0-beta.13). 
After updating it to new version (v0.1.0), it works well perfectly.
If anyone has problem like this, I recommend update the version of ionic-framework.
