### ISSUE TITLE
Bower doesn't worked

### ISSUE THREAD

**Issue by LeoLR** [zachsoft/Ionic-Material#112]
Hi!

I try to install ionic-material with bower but i've some problems with bower. 
![administrateur cwindowssystem32cmd exe](https://cloud.githubusercontent.com/assets/10087588/8694710/0fefb940-2ae1-11e5-85c5-d9980b520bae.jpg)

I've configured the npm proxy and edit my .bowerrc but that doesn't worked... 

If someone have a idea or can i install him without bower? 

Thank's!

**Comment by mavrick** [comment]
your connection to download the package is timing out. Check to make sure your date on your computer is set correctly and try again. If it still doesn't work just wait a little bit. It could be an issue between you and github.

I tried just now and this is the result:

![http://i.imgur.com/BdvN97b.png](http://i.imgur.com/BdvN97b.png)

**Comment by LeoLR** [comment]
I've edit the good file for bower but in the wrong folder... That works now ^^
Thank's!
