### ISSUE TITLE
Is your webzone down?

### ISSUE THREAD

**Issue by MichaelJCole** [zachsoft/Ionic-Material#12]
http://ionicmaterial.com/

Unable to load the webpage because the server sent no data.
Error code: ERR_EMPTY_RESPONSE

Tried from Thailand and my US vpn.

**Comment by zachsoft** [comment]
Thanks, I notified my host. It's prompting me to switch servers/hosts. I appreciate the courtesy of letting me know, thanks!

**Comment by MichaelJCole** [comment]
No worries.  Your project looks cool :-)

On Sun, Apr 5, 2015 at 5:32 AM, Zach Fitzgerald <notifications@github.com>
wrote:

> Thanks, I notified my host. It's prompting me to switch servers/hosts. I
> appreciate the courtesy of letting me know, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachsoft/Ionic-Material/issues/12#issuecomment-89672821>
> .
>



-- 
Michael Cole
http://Powma.com
