### ISSUE TITLE
Samples from ionicmaterial.com

### ISSUE THREAD

**Issue by KingStreetMike** [zachsoft/Ionic-Material#120]
Just a question regarding the samples on http://ionicmaterial.com/ whether the code used for 
Pre-built Layouts
such as 
Activity Feeds
Categories
...
Login
Profile

are available and if so, where from.

Thanks in advance for any assistance you can offer.

Mike

**Comment by SakyaStelios** [comment]
You can check the code with Browser Dev Tools

**Comment by KingStreetMike** [comment]
Thanks mate - I will resort to this. They look very impressive I must admit.

**Comment by JobaDiniz** [comment]
Here? https://github.com/zachsoft/Ionic-Material/tree/master/demo

**Comment by KingStreetMike** [comment]
Thanks Joba - but thats the thrones demo. All good - Im using Chrome inspector - its only the html I was after.
