### ISSUE TITLE
No project activity for 3 months, alternative available

### ISSUE THREAD

**Issue by delta98** [zachsoft/Ionic-Material#130]
I'm not sure if this project is still active and I think a lot of people want answers as to whether it's going to continue to be updated.

Until then I've been working on an alternative and it's approach differs from this project substantially otherwise I'd of picked this project up and tried to make it work. But a lot of people want to use Material Design in Ionic.

I'm releasing RC1 31st Aug and improvements and features will continue to be added for quite sometime.

Checkout https://github.com/delta98/ionic-material-design-lite

I appreciate jumping on this project and advocating for my own seems to be in bad taste, but no one is providing any answers or a solution.

**Comment by NoellyB76** [comment]
I'll give it a shot! If you need help, also, please let me know!

**Comment by LunarDevelopment** [comment]
:+1: I've made the switch to Lite already, great work @delta98

**Comment by delta98** [comment]
Let me know how you get on @LunarDevelopment, really interested in feedback at this stage on the run up to releasing RC 1

**Comment by jeveloper** [comment]
Pretty sad that they stopped working on it. Such a great landing page and then no work.

**Comment by oscarmcm** [comment]
Working on it now :)
