### ISSUE TITLE
Project based on this

### ISSUE THREAD

**Issue by Memleak2** [zachsoft/Ionic-Material#142]
I see this project is inactive.
Is however a good idea using just the template of demo to build an  app?
All working good?
Tnx for reply.

**Comment by delta98** [comment]
Alternative project here: https://github.com/delta98/ionic-material-design-lite

**Comment by oscarmcm** [comment]
@Memleak2 Hi, im working on the project now :)

**Comment by Memleak2** [comment]
Good news, i really like this material.

**Comment by oscarmcm** [comment]
thanks, just give me time. I will fix all the thing and make some improvements :)
