### ISSUE TITLE
animations

### ISSUE THREAD

**Issue by codingL3gend** [zachsoft/Ionic-Material#16]
when i have a list of more than 4-5 elements that are not all in view at the same time, the animation does not animate all of the elements so when i scroll through the list i see blank space where the remaining elements should be. when i remove the effects the list populates fine. any ideas why?

**Comment by guilhermedecampo** [comment]
@codingL3gend did you find out a way to trigger the other elements ?

**Comment by codingL3gend** [comment]
@guilhermedecampo I switched over to the alpha release version and that had fixed the issue that i was having.

**Comment by guilhermedecampo** [comment]
Cool @codingL3gend! Awesome that I could help. :smile:
