### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by shaulhadar** [zachsoft/Ionic-Material#2]
Hi man than looks great! I was wandering if there is going to be a tabs element, and sidemenu element also? That would be a great addition:)

**Comment by zachsoft** [comment]
Hey, thanks. Tabs and side menus have been part of the plan for this project. When I get some time, I'll try to integrate it into the source.

**Comment by shaulhadar** [comment]
Thanks Man! :)

**Comment by zachsoft** [comment]
Shaul, alpha is aimed at release end of week. In this upcoming version, I made sure side menu and tab support is provided the "ionic" way (no additional code needed). You'll be able to add the ink effect by just adding an "ink" class to the tabs/menu items - super simple. There will be a demo app in the release that will show this behavior. I'll follow up here after the release.

Just wanted to thank you for your patience and let you know to look out for the release in the coming week.

**Comment by shaulhadar** [comment]
Hi Zach, it took me some time, but I just got back to work on my apps, and I can see you have great progress!!

I am actually working on a WordPress posts app, and I choose ionic material for this;)
