### ISSUE TITLE
Centralize CSS

### ISSUE THREAD

**Issue by brandonjmckay** [zachsoft/Ionic-Material#20]
Hey, love the work!

I'm looking around for material design frameworks, and noticed that there a number of them; each of them building out the same type of CSS modules. There are a number of material frameworks, but each one is built for a specific JS framework. 
I'm wondering if it would be possible to centralize some of the similar CSS work into a separate project.

I'm not on ionic, but I really like what you're doing here.

Do you use `scss`, or another preprocessor? _(couldn't see any `.scss` files)_
Would you be interested in a project that focuses on the CSS elements in the material design spec, and leaves the JS stuff to other frameworks, or provides helper functions that other JS frameworks could use?

Just brainstorming right now, but this is something that I think could help create a larger toolset for all the material design focused projects.

**Comment by miguelcobain** [comment]
I also don't like how fragmentized material implementations are right now. Any step in creating something more universal is a huge plus. Every framework/library benefits from that.

**Comment by daMupfel** [comment]
:+1: please use scss since ionic uses scss too. Otherwise looking damn nice!

**Comment by raibutera** [comment]
@daMupfel @brandonjmckay  I've just added scss support.

**Comment by daMupfel** [comment]
Nice! Thank you!
