### ISSUE TITLE
ion-md-input directive missing

### ISSUE THREAD

**Issue by jimlei** [zachsoft/Ionic-Material#27]
While playing around with the demo app I noticed the login fields are missing. Since I absolutely love how material design handle the labels/placeholders I'd sure miss it from ionic-material.

![screenshot](https://cloud.githubusercontent.com/assets/4523053/7440818/451cd300-f0cb-11e4-95a2-9459d97ee1af.png)
see live at: http://ionicmaterial.com/demo/demo/www/#/app/login

**Comment by guilhermedecampo** [comment]
1+ for that

**Comment by mhartington** [comment]
I think what you're looking for is this.
https://github.com/mhartington/ion-md-input
Note, https://github.com/zachsoft/Ionic-Material/pull/25 adds this a dependency

**Comment by Alexintosh** [comment]
Nice!

On 16 May 2015 at 11:41, Mike Hartington <notifications@github.com> wrote:

> I think what you're looking for is this.
> https://github.com/mhartington/ion-md-input
> Note, #25 <https://github.com/zachsoft/Ionic-Material/pull/25> adds this
> a dependency
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachsoft/Ionic-Material/issues/27#issuecomment-102664963>
> .
>



-- 
*Alessio Delmonti *| *web* and *mobile* developer

*Save a tree. Print this e-mail only if it's necessary*

**Comment by raibutera** [comment]
Fixed, thanks to @mharington and @frederickjansen
