### ISSUE TITLE
Will There Be Any Demo With UI-Router ?

### ISSUE THREAD

**Issue by shaulhadar** [zachsoft/Ionic-Material#3]
Hello Zach, i was wandering if you are working on maybe a demo built on top of ionic, including angular setup, and ui-router configuration?
currently i can see only demos for seperate pages, but no router to change the pages, so i am not sure how to use the code in a regular project with a number of pages... any help would be appreciated :)

Thanks,
Shaul.

**Comment by zachsoft** [comment]
Definitely. The immediate aim is to sequence the animations with the version of ui-router that comes baked with Ionic. The goal is to not just initiate the sequence on state changes, but also provide events that will give control to invoke the start, pause, and clearing of animations at any state of your app's views.

**Comment by shaulhadar** [comment]
That's Sounds Great! :)
