### ISSUE TITLE
Feature Request - status bar color

### ISSUE THREAD

**Issue by shaulhadar** [zachsoft/Ionic-Material#39]
hi Zach , I would to add a wish for an implementation of the status bar plugin. in this way we could change status bar color on lollipop and it will look more professional.

thanks :)

**Comment by raibutera** [comment]
I'm pretty sure this is cordova specific?

**Comment by shaulhadar** [comment]
Hi raibutera, yeah, this is supposed to be working when adding the cordova status bar plugin... what i ment that if there was any starter code or any way to add this with ionic material, than it would be great.... you probably know this effect, all of the material apps in lollipop have it... and i think it's important for apps to look as much more material as they can :)
I will try and check if i can help in anything...

**Comment by raibutera** [comment]
Please check out the Ionic Framework related documentation on the status bar.


Ionic Material simply modifies (and extends) the values for Ionic colors (eg. `assertive`, `balanced` etc.) , so you can just use the status bar plug in as you would in any other Ionic project.




Hope that helps!
