### ISSUE TITLE
move ionic.material.ink and ionic.material.motion to their own services

### ISSUE THREAD

**Issue by raibutera** [zachsoft/Ionic-Material#58]
the current implementation relies on the global `ionic` object which is bad for mocking/testing/reusability/etc.

I suggest we create `$ionicMaterialInk` and `$ionicMaterialMotion` providers.

**Comment by guilhermedecampo** [comment]
Pretty cool @raibutera

**Comment by heradonbenin** [comment]
please download the source code. i follow the step on github.
when i try start the app in browser i get this error : [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module ionic-material due to:
Error: [$injector:nomod] Module 'ionic-material' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. please can u help me?

**Comment by mubasshir** [comment]
any update on this? I'm stuck...

**Comment by raibutera** [comment]
@heradonbenin @mubasshir ionicMaterialInk and ionicMaterialMotion services were introduced in 0.4.0

**Comment by mubasshir** [comment]
but its available in your current code, I'm confused, whether remove or keep

**Comment by raibutera** [comment]
? please rephrase

**Comment by mubasshir** [comment]
I just downloaded your code, ran ionic server --lab. Its still giving same error. Should I remove ink completely?

**Comment by raibutera** [comment]
Did you run bower install etc

**Comment by heradonbenin** [comment]
hi i run bower install..this is the full error message a get. 

Error: [$injector:unpr] Unknown provider: ionicMaterialInkProvider <- ionicMaterialInk <- LoginCtrl
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=ionicMaterialInkProvider%20%3C-NaNonicMaterialInk%20%3C-%20LoginCtrl
    at REGEX_STRING_REGEXP (http://localhost/Ionic-Material-master-2/demo/www/lib/ionic/js/ionic.bundle.js:7988:12)
    at http://localhost/Ionic-Material-master-2/demo/www/lib/ionic/js/ionic.bundle.js:11922:19
    at Object.getService [as get] (http://localhost/Ionic-Material-master-2/demo/www/lib/ionic/js/ionic.bundle.js:12069:39)
    at http://localhost/Ionic-Material-master-2/demo/www/lib/ionic/js/ionic.bundle.js:11927:45
    at getService (http://localhost/Ionic-Material-master-2/demo/www/lib/ionic/js/ionic.bundle.js:12069:39)
    at invoke (http://localhost/Ionic-Material-master-2/demo/www/lib/ionic/js/ionic.bundle.js:12101:13)
    at Object.instantiate (http://localhost/Ionic-Material-master-2/demo/www/lib/ionic/js/ionic.bundle.js:12118:27)
    at http://localhost/Ionic-Material-master-2/demo/www/lib/ionic/js/ionic.bundle.js:16387:28
    at IonicModule.controller.self.appendViewElement (http://localhost/Ionic-Material-master-2/demo/www/lib/ionic/js/ionic.bundle.js:47357:24)
    at Object.IonicModule.factory.ionicViewSwitcher.create.switcher.render (http://localhost/Ionic-Material-master-2/demo/www/lib/ionic/js/ionic.bundle.js:45614:41)

**Comment by zeeshanjan82** [comment]
I get the same error. Any fix for that?

**Comment by mubasshir** [comment]
hey, now when bower install freshly downloaded code, I'm getting following error.
```
Additional error details:
remote: Repository not found. fatal: repository 'https://github.com/fians/Ink.git/' not found
```
attached screenshot of same
![untitled](https://cloud.githubusercontent.com/assets/3141806/7878450/4c35d0ee-0604-11e5-8f7e-8d251fbfe77a.png)

if repository not available, why ain't you removing it?

**Comment by mavrick** [comment]
Make sure the version of ionic-material inside your bower.json file is latest then try again.

**Comment by mavrick** [comment]
I have created a pull request for ./demo/bower.json #76

**Comment by mubasshir** [comment]
Can you specify which version we should put?


Mubasshir Pawle | COO | Eiosys Inc
Mobile: +91-9172080729 | Land line: +91-22-6464-6561

On Fri, May 29, 2015 at 7:23 pm, zachsoft/Ionic-Material
<reply@reply.github.com>
wrote:
Make sure the version of ionic-material inside your bower.json file is latest
then try again.

—
Reply to this email directly or view it on GitHub
[https://github.com/zachsoft/Ionic-Material/issues/58#issuecomment-106808947] .[https://github.com/notifications/beacon/AC_wrvGdrEThzAQCqr9qmFBEZzJOnIuFks5oOGbUgaJpZM4EfTUv.gif]

**Comment by ityao** [comment]
I find the error is from demo entry miss inject the "ionic-material", just modify the app.js with follow line at line 7:
angular.module('starter', ['ionic', 'starter.controllers', 'ionic-material', 'ionMdInput'])

**Comment by MarlinDoo** [comment]
@ityao +1

**Comment by herve1976** [comment]
I tried ityao solution but it s still not working for me.

**Comment by uttesh** [comment]
i had the same issue, solved by  referring the "ionic.material.js" present in the "dist" folder,which as "ionicMaterialInk", "ionicMaterialMotion" providers. this providers are missing in the parent demo folder "ionic.material.min.js" folder.

changes made to solve the provider issue :

index.html : 

 <script src="lib/ionic-material/dist/ionic.material.min.js"></script>

app.js :

angular.module('starter', ['ionic', 'starter.controllers','ionMdInput','ionic-material'])

hope this will help.

**Comment by herve1976** [comment]
I was able to make the demo working using this index.html:

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>
    <link href='https://fonts.googleapis.com/css?family=RobotoDraft:400,500,700,400italic' rel='stylesheet' type='text/css'>
    <link href="lib/ionic/css/ionic.css" rel="stylesheet">
    <link href="lib/ion-md-input/css/ion-md-input.min.css" rel="stylesheet">
    <link href="lib/ionic-material/dist/ionic.material.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <script src="lib/ionic/js/ionic.bundle.js"></script>
    <script src="lib/ionic-material/dist/ionic.material.js"></script>
    <script src="lib/ion-md-input/js/ion-md-input.min.js"></script>
    
    <script src="cordova.js"></script>
    
    <script src="js/app.js"></script>
    <script src="js/controllers.js"></script>
</head>
<body ng-app="starter">
    <ion-nav-view></ion-nav-view>
</body>
</html>
