### ISSUE TITLE
Can't get ng-repeat to display on modified friends page

### ISSUE THREAD

**Issue by phaggood** [zachsoft/Ionic-Material#65]
I changed the friends page to display an array of friends objects from FriendCtrl, plugging in the repeat it never displays, if I remove the "list animate-*" div the list of friends displays.

-- in controller

        $scope.friends = [
            {
                img: "img/jon-snow.jpg",
                name: "Jon Snow",
                desc: "Da illest illegitimate",
                iclass: "icon ion-chatbubble muted"
            },
            ...
         ]

-- friends.html after modifications:

    <ion-view view-title="Friends">
    <ion-content ng-class="{expanded:isExpanded}">
        <div class="content has-header">
            <div class="list animate-fade-slide-in-right">

                <div ng-repeat="friend in friends">
                    <a href="#/app/profile" class="item item-avatar item-icon-right">
                        <img ng-src="{{friend.img}}">

                        <h2>J{{friend.name}}</h2>

                        <p>{{friend.desc}}</p>
                        <i ng-class="friend.iclass"></i>
                    </a>
                </div>
            </div>
        </div>
    </ion-content>
    </ion-view>

**Comment by raibutera** [comment]
Please see the documentation for activating animations

**Comment by phaggood** [comment]
I checked http://ionicmaterial.com/demo/ which had lots of code for components but nothing about animations.

**Comment by raibutera** [comment]
Check the sidebar. It's under 'motion'

**Comment by phaggood** [comment]
quick googling suggests two ways to do that, neither of which looks to be a 'best practice'

http://www.bennadel.com/blog/2592-hooking-into-the-complete-event-of-an-ngrepeat-loop-in-angularjs.htm
http://stackoverflow.com/questions/22384078/angularjs-manipulating-the-dom-after-ng-repeat-is-finished

**Comment by raibutera** [comment]
Not to be mean, but there's a big discussion on this topic in another issue (Issue #46)

https://github.com/zachsoft/Ionic-Material/issues/46

If I'm wrong, please ask to reopen.

**Comment by phaggood** [comment]
Yeah, just before you closed it I found a relatively simple solution similar to the first reply at #46 on stackoverflow - http://stackoverflow.com/a/13775176/4330496

**Comment by raibutera** [comment]
Please move all discussion to #46 so it's easier to find for people in the
same boat as you :)
