### ISSUE TITLE
Refactor the project

### ISSUE THREAD

**Issue by oscarmcm** [zachsoft/Ionic-Material#67]
Hey @raibutera @zachsoft i have some ideas, let me know what do you think about this:

* Create a chat room [gitter](https://gitter.im/)
* Move the project to a Github Organization, I think that is this more easy for the things that we are using like the website, the roboto font, the main project and other custom things.
* Create a repo with a demo app using Ionic-Material.

**Comment by raibutera** [comment]
I've asked for the organisation. I'm waiting for a reply. The demo app
already exists but maybe should be moved to another repo. Gitter would be
cool

**Comment by oscarmcm** [comment]
Yeah, the demo app already exist, but we need things more clear, I think that we need move the demo to another repo and don't combine this with the main project. @raibutera then? create the gitter room? or wait for @zachsoft

**Comment by raibutera** [comment]
I've made the gitter room @oscarmcm

**Comment by oscarmcm** [comment]
Ultra Cool :smile: thanks @raibutera

**Comment by delta98** [comment]
Where's the room?

**Comment by oscarmcm** [comment]
@delta98 go [here](https://gitter.im/zachsoft/Ionic-Material?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
