### ISSUE TITLE
enable to install using bower

### ISSUE THREAD

**Issue by heradonbenin** [zachsoft/Ionic-Material#71]
please i'm enable . get this error  Package ionic-materia not found

**Comment by raibutera** [comment]
I can install using bower just fine

**Comment by oscarmcm** [comment]
@heradonbenin I think it's a typo error, mind you if you've written in this way 

```shell
bower install ionic-material
```
http://bower.io/search/?q=ionic-material

**Comment by heradonbenin** [comment]
sorry , it ok now.... thanks... it my first time i build mobile apps with angularjs.

**Comment by oscarmcm** [comment]
Don't worry :smiley:
