### ISSUE TITLE
bower install ionic-material issue

### ISSUE THREAD

**Issue by moeinalmasi** [zachsoft/Ionic-Material#75]
Once trying to install ionic-material through bower, gets following error, seems ionic does not support bower anymore, any workaround?

ERROR MESSAGE
bower not-cached    git://github.com/driftyco/ionic-bower.git#1.0.0
bower resolve       git://github.com/driftyco/ionic-bower.git#1.0.0
bower not-cached    git://github.com/zachsoft/Ionic-Material.git#*
bower resolve       git://github.com/zachsoft/Ionic-Material.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/driftyco/ionic-bower.git", exit code of #3221225781

**Comment by abrararies** [comment]
I get this

bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://github.com/fians/Ink.git", exit code of #128

Additional error details:
remote: Repository not found.
fatal: repository 'https://github.com/fians/Ink.git/' not found

**Comment by mavrick** [comment]
Make sure the version of ionic-material inside your bower.json file is latest then try again.

**Comment by mavrick** [comment]
I have created a pull request for ./demo/bower.json #76

**Comment by moeinalmasi** [comment]
Thanks!!! bower.json content is now

{
  "name": "HelloIonic",
  "private": "true",
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.0.0-rc.2",
      "ionic-material": "0.4.2",
      "ion-md-input": "0.0.2"
  }
}
