### ISSUE TITLE
Installation via bower

### ISSUE THREAD

**Issue by lahaxearnaud** [zachsoft/Ionic-Material#8]
Hello,

Can you register Ionic-material on bower ?

http://bower.io/docs/creating-packages/#register

thanks,

Arnaud

**Comment by Jeoffrey54** [comment]
+1.

**Comment by aerotoad** [comment]
+1

**Comment by benamib** [comment]
+1

**Comment by brunogonncalves** [comment]
+1

**Comment by Santino-Wu** [comment]
+1 Up

**Comment by zachsoft** [comment]
Thanks guys. It's public and registered now. Install via: bower install ionic-material
