### ISSUE TITLE
Demo shows white screen when run on browser and devices

### ISSUE THREAD

**Issue by Saumik** [zachsoft/Ionic-Material#91]
I'm trying to run the demo in Mac Yosemite with Ionic and Cordova 5.  At Ionic-Material/demo running  bower install ionic-material causes an { Failed to execute "git ls-remote --tags --heads https://github.com/fians/Ink.git", exit code of #128 remote: Repository not found. fatal: repository 'https://github.com/fians/Ink.git/' } to appear. As in https://github.com/zachsoft/Ionic-Material/issues/18 I tried removing the Ionic-Material folder present originally in the demo, then it loaded without an error on bower install but on running 'ionic serve' it still showed a white screen.  I even tried copying the original demo files of the lib/Ionic-Material ( the json, css and js files) into the new installed lib/Ionic-Material folder, yet it showed a white screen.  Can anyone please solve the error or put up detailed instructions for it.

PS: I'm an ionic newbie and just found out Ionic-Material, you guys just saved a ton of my time. Thanks and Much Love!

**Comment by Saumik** [comment]
Solved it. It seems the demo is not updated with the new version of ionic material. Will put up the updated version.

**Comment by oscarmcm** [comment]
@Saumik I hope everything will work, if you have any problems, please ask we are here to help :smile:

**Comment by shyambv** [comment]
@Saumik Did it work for you? I am getting the same error.

**Comment by nathanyeung** [comment]
No it didn't work 😒

On Wednesday, August 26, 2015, shyambv <notifications@github.com> wrote:

> @Saumik <https://github.com/Saumik> Did it work for you? I am getting the
> same error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachsoft/Ionic-Material/issues/91#issuecomment-135207163>
> .
>


-- 
Nathan Yeung
Coldwell Banker Apex, Realtors
7290 Virginia Parkway Suite 2400
McKinney, TX 75071
Cell: 972-251-0887
Email: nathan.yeung@coldwellbanker.com

**Comment by lucianocosta** [comment]
The demo has an outdated version of ionic-material. The offending repo (https://github.com/fians/Ink.git) is listed as dependency in "lib/ionic-material/.bower.json". For now, just replace that line with this one:
```
"waves": "0.6"
```
Then run "bower install" again.
