### ISSUE TITLE
Ion-md-input working error!

### ISSUE THREAD

**Issue by dungphanxuan** [zachsoft/Ionic-Material#96]
Hello, i try to use ion-md-input but the view not show like good.
![ion-md-input](https://cloud.githubusercontent.com/assets/10725732/8277707/9f5f4f40-18ef-11e5-8ab5-bf9c6057b6d1.PNG)

**Comment by codingL3gend** [comment]
the ion-md-input looks to render fine, is the alignment off for you? or are you expecting it to look differently?

**Comment by liuwenzhuang** [comment]
So do I. It seems that the background of ion-md-input will be change by ion-material, I'm not sure. But use ion-md-input alone perform well.
